### ISSUE TITLE
filling collectd_plugins on debian

### ISSUE THREAD

**Issue by karamelichkin** [robertdebock/ansible-role-collectd#4]
# Describe the bug

when you try to configure a write_graphite plugin on debian it throws error with 'Install collectd plugin dependencies'-task

## Output

FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'write_graphite'. 'dict object' has no attribute 'write_graphite'\n\nThe error appears to be in '/home/ansible/.ansible/roles/robertdebock.collectd/tasks/plugins.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: plugins | Install collectd plugin dependencies\n  ^ here\n"}

cause write_graphite plugin is part of main package or (collectd-utils) (on debian)

## Playbook

```yaml
---
    vars:
      collectd_basic_plugins:
        - interface
      collectd_conf_hostname: "{{ ansible_hostname }}"
      collectd_conf_include_dir: /etc/collectd/collectd.conf.d
      collectd_plugins:
        - name: write_graphite
          config: |
              <Node "{{ ansible_hostname }}">
              Host "xxxxxxxx"
              Port "2003"
              Protocol "tcp"
              LogSendErrors true
              Prefix "collectd."
              </Node>
```

## Environment

- Control node OS: FreeBSD ansible 14.0-RELEASE-p6
- Control node Ansible version: core 2.15.6
- Managed node OS: Debian GNU/Linux 12 bookworm

workaround fix is commenting task
- name: plugins | Install collectd plugin dependencies
